name: 'Build Totem (with mouse)'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_dongle","totem_left","totem_right"]'
      kconfig: '["CONFIG_ZMK_POINTING=y"]'
